--INITIALISATION TABLE ACCOUNT
INSERT INTO ACCOUNT(ACCOUNT_ID,ACCOUNT_TYPE) VALUES (1,'LivretA');
INSERT INTO ACCOUNT(ACCOUNT_ID,ACCOUNT_TYPE) VALUES (2,'Cheque');

--INITIALISATION TABLE UTILISATEURS
INSERT INTO UTILISATEUR(USER_ID, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, IS_ENABLED) values (1, 'aurelien', 'betourne', 'aurelienbtratgmaildotcom', 'password1', 0);
INSERT INTO UTILISATEUR(USER_ID, FIRSTNAME, LASTNAME, EMAIL, PASSWORD, IS_ENABLED) values (2, 'sofiane', 'ziane', 'szianeatgmaildotcom', 'password1', 1);

